#
# SPDX-FileCopyrightText: 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

[versions]
agp = "9.1.0"
crcalc = "1.0"
generatebp = "+"
gridlayout = "1.1.0"
material = "1.14.0-alpha10"
webkit = "1.15.0"

[libraries]
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
crcalc = { group = "com.hp", name = "crcalc", version.ref = "crcalc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
lineageos-generatebp = { id = "org.lineageos.generatebp", version.ref = "generatebp" }
